### ISSUE TITLE
Clicking the Subscribe button on the Events page no longer works

### ISSUE THREAD

**Issue by cwant** [ElixirTeSS/TeSS#1046]
**Describe the bug**

Clicking the Subscibe button on the events page is supposed to show a menu ("Subscribe via email", etc), but now it doesn't do anything.

**To Reproduce**

  1. Go to https://tess.elixir-europe.org/events
  2. Click on "Subscribe"
  3. The click in step 2 has no effect

**Expected behavior**

A menu should pop up with some options

**Desktop (please complete the following information):**
  - OS: Ubuntu 24.04
  - Browser chrome
  - Version 130.0.6723.91 (Official Build) (64-bit)

**Additional context**

Noticed it wasn't working on my fork, confirmed it isn't working upstream too.

**Comment by fbacall** [comment]
I think this is resolved by #1048
