### ISSUE TITLE
Add scrapers for (soon-to-be) Official ELIXIR-UK Training Resources

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#200]
- http://bioinfotraining.bio.cam.ac.uk/ and
- http://training.csx.cam.ac.uk/bioinformatics/Event-timetable
- http://www.birmingham.ac.uk/bmtc
- https://genomics.ed.ac.uk/work-with-us/bioinformatics/training

**Comment by knirirr** [comment]
What's the relationship between the first two? Are they separate resources or is the latter a better representation of the former?
