### ISSUE TITLE
Add twitter feed field for content providers

### ISSUE THREAD

**Issue by anenadic** [ElixirTeSS/TeSS#232]

**Comment by njall** [comment]
The logos of organizations are consistently used on their Twitter profile. 
Adding a twitter handle field (as well as  being able to display their latest news) would allow us to dynamically load the latest logo of the organization. 

On the Content Provider edit form, once a user inputs a twitter handle, a checkbox should be presented asking whether they would like to set the logo from twitter.


This is a feature I've seen from the bank _Monzo_. It sources company logos to show on transactions by registering their twitter handle. This way it self-updates when companies rebrand.
