### ISSUE TITLE
Add scrapers for ELIXIR-PT (Portugal)

### ISSUE THREAD

**Issue by anenadic** [ElixirTeSS/TeSS#235]
See Pedro Fernandez''s email below:

Dear Aleks,

Thanks for this. I do need your help. And your patience.
I hope that you find it normal, a programme like GTPB working since 1999 has adopted several forms of registering materials. Our instructors come from very different places with different habits. For a long time we used to make CD's for people to take home. Lately we ask them to use github to develop the materials allowing me to cooperate remotely. Then, when each course ends, we ask them to polish the repository and we also record the content of the shared disk in the room (To Participant), so that people can download from home. This is good but I would say that we are in transition, still probing if it needs improvement.

Two recent examples:
http://gtpb.igc.gulbenkian.pt/bicourses/NDARC16/   Website
https://github.com/bioinformatics-core-shared-training/ndarc16
http://gtpb.igc.gulbenkian.pt/bicourses/NDARC16/NDARC16_doc.zip  To Participant
http://mygoblet.org/training-portal/courses/ngs-data-analysis-rnaseq-chipseq

http://gtpb.igc.gulbenkian.pt/bicourses/PDA16/    Website
 http://gtpb.igc.gulbenkian.pt/bicourses/PDA16/PDA16_doc.zip     ~200kB
 http://gtpb.igc.gulbenkian.pt/bicourses/PDA16/PDA16_data.zip    ~1.1GB

In the PDA16 case above, I have asked the instructors (authors) to  upload in GOBLET. BUT.... NOT YET DONE!

Most past courses ended  with the zip file with the To Participant content.

We are hiring someone to help with ELIXIR training and, as we adopted the GTPB format, this person will also organise all our materials.
I have a certain hope on agreeing with you which way will be best to proceed.
Maybe we can even think of keeping a local repository but we can also use Goblet while there is space there.
Your advice is more than welcome.

Best
Pedro

**Comment by anenadic** [comment]
Contact: Pedro Fernandes <pfern@igc.gulbenkian.pt>

**Comment by njall** [comment]
ELIXIR Portugal scraped:
https://tess.elixir-europe.org/content_providers/elixir-portugal
