### ISSUE TITLE
Add scrapers for ELIXIR-FR (France)

### ISSUE THREAD

**Issue by anenadic** [ElixirTeSS/TeSS#238]
Dear all,

Thank you very much for your message.
 In fact 90% of our material is in French and dispersed into multiple sites.  By the way, we have some training material in English which includes pdf, ppt and github repository, example:

-> Quick tutorial to install an IFB cloud VM with chip-seq tools and run a sample workflow with snakemake 

https://github.com/rioualen/gene-regulation/blob/master/doc/install_protocols/IFB_cloud_presentation_and_usage.Rmd
Written by Claire Rioualen. 

-> https://cloud.france-bioinformatique.fr/xport/numbio/2-juin/blanchet-cloud-IFB.pdf by Christophe  Blanchet
or
-> http://www.france-bioinformatique.fr/sites/default/files/ibi2_0.zip

Please let me know which is the best way to add the materials. I remember something about xml files. If you could  please send me a template from another website, that would be perfect.

I will be happy to participate on 26th May.

Kind regards

Victoria

**Comment by anenadic** [comment]
Contact: DOMINGUEZ Victoria <victoria.dominguez@france-bioinformatique.fr>

**Comment by njall** [comment]
IFB Scraped: https://tess.elixir-europe.org/content_providers/ifb-french-institute-of-bioinformatics
