### ISSUE TITLE
Node IDs looking for internal ID. Need to look for country code

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#367]
node_ids is the internal id of the node objects. It was easy for UI stuff where the dropdown list populates the values, but not good for the API. We need to have the dropdown list pass country codes e.g. BE, UK, CZ, and then the controller to find node with said country code and associate it with the material.

**Comment by fbacall** [comment]
Should we use country codes or names?

Currently both the UK and EMBL-EBI nodes share the "GB" country code.
