### ISSUE TITLE
Generate CSV/Excel spreadsheet of each nodes training events

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#389]
Create a function (accessed through https://tess.elixir-europe.org/events/get_csv or something) that  generates a CSV or excel workbook that follows creates this spreadsheet 

https://docs.google.com/spreadsheets/d/1lUVZSarRpvH_3mR5HOKGK9nM1z1njkZdEP_9JHfRVTk/edit#gid=2020231584

With all the titles:
Title	Funding Organizing node	Event start	Duration (days)	Location	No. of participants	No. of overall applicants	No. of trainers	Organizer
Filled in with the events from that node; leaving blank all the fields we can't fill in

**Comment by fbacall** [comment]
Look to see how google sheets API works
