### ISSUE TITLE
Revisit sitemap

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#421]
Not sure the sitemap works correctly. Certainly the links point to elixir-uk not elixir-europe - but after a good length of time Google hasn't displayed it correctly. Ensure it adheres to sitemap standards https://www.sitemaps.org/protocol.html

**Comment by knirirr** [comment]
The links should be fixable by changing the setting in this config. file:

https://github.com/ElixirUK/TeSS/blob/master/config/sitemap.rb

**Comment by fbacall** [comment]
Should probably change the hard-coded "host" to parse out the hostname from TeSS::Config.base_url
