### ISSUE TITLE
Menu bar is for the child node when parent node is selected after adding new node

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#434]
So you add a node - fill in form - hit enter.
Add a child node to that node - fill in form - hit enter.
The parent node is selected, but the menu bar only allows 'add node' - not 'add child node'. It's possible it's loading the menu of the child and selecting the parents. Should probably select the child really. It's not a big issue as you can select the canvas, select the node again, and the correct menu appears

**Comment by fbacall** [comment]
This is semi-related to #430

I changed the code so it would select the newly created node, but then the node would disappear because of the bug
