### ISSUE TITLE
Update production server apache

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#460]
Upgrade to Apache version 1.3.22 or later

The CSC scan of their machines showed a vulnerability in our server. We must upgrade apache versions to fix it

**Comment by fbacall** [comment]
I've disabled the part of the config that was exposing this.

**Comment by knirirr** [comment]
Looks like both TeSS machines are on 2.4.7-1ubuntu4.13.
Should this perhaps be closed if the relevant section has been disabled in any case?
