### ISSUE TITLE
Semi-automatic provider import 

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#464]
Have a specialist bulk import page

- User puts in a URL where resources can be found. This could be an ICS file, a sitemap for a website with schema.org annotations, an RSS feed, etc
- They then select what that type is
- Depending on format, a scraper initiates and downloads and extracts the resource
- The resulting set of events and materials are displayed in a table. There is another column giving the user the ability to remove a row from the table.
- A toggle to allow the user to say whether this should be performed everyday is available
- A submit button is at the bottom of the page. This submits any unrejected resources. 
- The user can also fill in content provider information or select an existing content provider. 

Questions to come back to:

- Where should this page be located? e.g.  providers/new users/bulk-import /bulk-import?
- Should users be able to specify they never want a resource added if they check the run daily checkbox?

**Comment by njall** [comment]
For ICS parsing
http://www.elixir-czech.cz/events/workshops-and-courses
http://software-carpentry.org/workshops.ics
https://calendar.google.com/calendar/ical/oe7bqnaf44l0eg20lj5c7n1te4%40group.calendar.google.com/public/basic.ics
http://www.inab.org/training/calendar/export_execute.php?userid=2&authtoken=245644be1420086102e7c7a8d6ebe11c4515d405&preset_what=all&preset_time=custom

**Comment by njall** [comment]
@fbacall Do you reckon you could get this finished by 2nd October? There's a Bioschemas meeting then and it would be great to be able to show this as a visual demonstration of how schema.org aggregation works

**Comment by fbacall** [comment]
Probably, but depends on what you would consider "finished".

Finding and adding events and materials is almost done. Things like: 
* reporting back any errors (like Google's structured data testing tool does)
* crawling through multiple pages
* scheduling automatic import

might not be doable by then
