### ISSUE TITLE
TeSS as a Proxy

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#468]
Allow TeSS to act as a proxy. There will be widgets made by other people that present links to TeSS resources. They should direct the user to the end resource, but in order to capture the usage of these widgets - they should go to TeSS first and redirect automatically.
 
Not sure the best way to do this. Maybe paramatise the TeSS resource e.g.
`https://tess.elixir-europe.org/events/my-event?redirect=true`
or have a redirect endpoint
`https://tess.elixir-europe.org/redirect?url=https://somedomain.org/event-name`

The latter seems to be the most commonly used but the former would make statistics easier to aggregate

**Comment by fbacall** [comment]
Probably also needs a parameter to identify which widget is being used

**Comment by rajido** [comment]
"https://tess.elixir-europe.org/events/my-event?redirect=true" could work quite easily if events had an identifier

**Comment by njall** [comment]
https://tess.elixir-europe.org/events/my-event?redirect=true&widget=organization_name
