### ISSUE TITLE
API action - event count

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#469]
ELIXIR Europe website shows events from TeSS. They want to be able to have a button next to the event saying 'see N more events like this' which would query TeSS
e.g.
**Some Bioinformatics Conference 2017**  | link to source | [see 4 more events like this in TeSS](https://tess.elixir-europe.org/events?event_types=Meetings+and+conferences&scientific_topics=Bioinformatics)

To do this we'd need an API action (e.g. events/count) that would behave with filter parameters the same way the index action would - but return only the count and the URL that would take the user to that search.

**Comment by knirirr** [comment]
I've moved this to the required place. However, there's a problem where an original URL such as:

/events/count?event_types=Workshops+and+courses&scientific_topics%5B%5D=Data+mining&scientific_topics%5B%5D=Epigenetics

Produces a search URL like this:

/events?event_types=Workshops+and+courses\u0026scientific_topics%5B%5D=Data+mining\u0026scientific_topics%5B%5D=Epigenetics

...for some reason all the ampersands get shown as unicode. Any suggestions on fixing this welcome.

**Comment by fbacall** [comment]
You can get the index URL like this:
```
events_url(params.slice(:q, *Event.facet_fields))
```

**Comment by knirirr** [comment]
The problem of & being converted to \u0026 still occurs even when using events_url(), though I didn't use that exact formulation.

**Comment by fbacall** [comment]
I actually think it's OK as it is. I tried parsing the JSON returned from our count URL using both JQuery and ActiveSupport and it parsed `\u0026` back into ampersands

**Comment by knirirr** [comment]
Thanks. If it parses successfully then could this be closed?
