### ISSUE TITLE
Hide Node and Package pages

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#470]
Hide the node and packages pages from the header. The pages themselves can still be accessed but the links to them should be taken away. This is because no-one is functionally using the packages and we should be encouraging them to structure their packages using workflows. The nodes pages all look very bare and unappealing and suggest nodes aren't doing anything. 

Add a note on the front page that explains why they have been hidden.

Attention Alert: 
The ELIXIR Node pages will be hidden while we improve the coverage and extent of each nodes registered training resources. If you would like to find out what each ELIXIR Node provides so far, you can filter on the [events](https://tess.elixir-europe.org/events) and [materials](https://tess.elixir-europe.org/materials) pages. 

The packages page has been removed as its functionality and much more have been incorporated into [workflows](https://tess.elixir-europe.org/workflows) feature.

**Comment by fbacall** [comment]
Should we still display the "Packages" tab on the user profile?
