### ISSUE TITLE
Be able to 'Favourite' resources

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#474]
It would be good to add favouriting/starring functionality next to workflows, events, and materials now that we've scrapped the confusing and little-used packages stuff... This would be similar to how myExperiment did it @fbacall 

The user would be able to click a hollow star outline at the top of a resource pages they find interesting. This will call an API action using AJAX that sets the star to coloured in and creates an association between that user and that resource in the database. Clicking again would remove the association / make the star hollow again.

The user can then view their favourited items as the first tab on their profile (where their resources are currently listed). And maybe also have a star icon in the user-options bar like so

![screen shot 2017-08-01 at 14 50 55](https://user-images.githubusercontent.com/860475/28828488-d93b66d4-76c8-11e7-8d84-bafb46fab4eb.png)

**Comment by fbacall** [comment]
Is this a user request? In my experience of myexp/SEEK, nobody really uses the favourites system, and just use browser bookmarks if anything.
