### ISSUE TITLE
Trial Nominatim 

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#478]
To get around Google maps ToS issues. Try configuring Geocoder to use Nominatim. nominatim.openstreetmap.org adding a 1 second delay between each request. Compare outputs between using google places and Nominatim ran with the same events scraper (maybe ELIXIR_events scraper). 

If Nominatims performance is reasonably comparable with Google places; implement a rake task in TeSS that uses sidekiq to add nominatim searches for every event that does not already have latitude and longitude values.

The returned results will get stored as edit suggestions to the event as has been done with the Annotator Web Service

**Comment by knirirr** [comment]
Here's what the Elixir event scraper produces when the lookup is either Google or Nominatim:

`
N: ELIXIR Luxembourg – Launch Event, 49.501954700000, 5.94303 | G: ELIXIR Luxembourg – Launch Event, 49.5019547, 5.9430323, 
N: ELIXIR HoNs meeting, 46.7985624, 8.2319736,                | G: ELIXIR HoNs meeting, 46.818188, 8.227512, 
N: Translational Medicine 2017, 49.8167003, 15.4749544,       | G: Translational Medicine 2017, 49.81749199999999, 15.472962,
N: 4th International Systems Biomedicine Symposium - Impact o | G: 4th International Systems Biomedicine Symposium - Impact o
N: ELIXIR Innovation and SME Forum: Data-driven innovation in | G: ELIXIR Innovation and SME Forum: Data-driven innovation in
N: ELIXIR TrCG and TeCG F2F meeting, 46.603354, 1.8883335,    | G: ELIXIR TrCG and TeCG F2F meeting, 46.227638, 2.213749, 
N: 2nd CORBEL Annual General Meeting, 52.384327600000, 4.9008 | G: 2nd CORBEL Annual General Meeting, 52.38432760000001, 4.90
N: BioData World Congress 2017, 52.07907325, 0.18435961434424 | G: BioData World Congress 2017, 52.0785333, 0.1861349, 
N: ELIXIR Board meeting (Paris), 46.603354, 1.8883335,        | G: ELIXIR Board meeting (Paris), 46.227638, 2.213749, 
N: ELIXIR Innovation and SME Forum: Rare Diseases and Persona | G: ELIXIR Innovation and SME Forum: Rare Diseases and Persona
N: ELIXIR HoNs Teleconference, , ,                            | G: ELIXIR HoNs Teleconference, , , 
N: ELIXIR Board meeting (Tel Aviv), 32.085299900000, 34.78176 | G: ELIXIR Board meeting (Tel Aviv), 40.6331249, -89.3985283, 
N: ELIXIR All Hands 2018, 52.50367365, 13.3520901499604, 1078 | G: ELIXIR All Hands 2018, 52.5038914, 13.3522162, 
N: ELIXIR Board meeting (Ljubljana), 45.8133113, 14.4808369,  | G: ELIXIR Board meeting (Ljubljana), 46.15124099999999, 14.99
N: ELIXIR Board meeting (Bergen), 60.5000209, 9.0999715,      | G: ELIXIR Board meeting (Bergen), 60.47202399999999, 8.468946
N: Benchmarking: Incentives and Best Practices across Scienti | G: Benchmarking: Incentives and Best Practices across Scienti
N: 5th International Summer School/BYOD event around Rare Dis | G: 5th International Summer School/BYOD event around Rare Dis
N: ELIXIR-EXCELERATE Train the Trainer, 40.768711800000, 14.7 | G: ELIXIR-EXCELERATE Train the Trainer, 40.76871180000001, 14
N: Bioschemas meeting, 52.07907325, 0.184359614344246,        | G: Bioschemas meeting, 52.0785333, 0.1861349, 
N: ELIXIR biocontainers hackathon, 46.9670155, 4.3058199, 714 | G: ELIXIR biocontainers hackathon, 48.8445394, 2.344079, 
N: European Galaxy Administrator Workshop, 60.5000209, 9.0999 | G: European Galaxy Administrator Workshop, 60.47202399999999,
N: ELIXIR Webinar on ELIXIR Data Platform, , ,                | G: ELIXIR Webinar on ELIXIR Data Platform, , , 
N: ELIXIR Webinar: The transfer of large volume, electronic,  | G: ELIXIR Webinar: The transfer of large volume, electronic, 
N: ELIXIR Webinar:  Referencing of Data Using Identifiers, ,  | G: ELIXIR Webinar:  Referencing of Data Using Identifiers, , 
N: ELIXIR Webinar: Improvements to Ensembl, , ,               | G: ELIXIR Webinar: Improvements to Ensembl, , , 
N: ELIXIR Webinar: Visualisation of rare disease genomics dat | G: ELIXIR Webinar: Visualisation of rare disease genomics dat
N: ELIXIR Webinar on the MoldatainRD Implementation Study, ,  | G: ELIXIR Webinar on the MoldatainRD Implementation Study, , 
N: ELIXIR Webinar on the Proteome Implementation Study, , ,   | G: ELIXIR Webinar on the Proteome Implementation Study, , , 
N: ELIXIR Webinar on the Systems Biology Implementation Study | G: ELIXIR Webinar on the Systems Biology Implementation Study
N: ELIXIR Webinar on the Sustainability Implementation Study, | G: ELIXIR Webinar on the Sustainability Implementation Study,
`

**Comment by knirirr** [comment]
I was able to get lat/lon for 59 of the 70 events without these values which actually had some details as to the country or city they were in, using Nominatim. So this may be workable if can deal with the edit suggestions.

**Comment by knirirr** [comment]
@fbacall has merged this into master.
