### ISSUE TITLE
Design new front page

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#479]
Front page needs redesigning. Look at examples from edx.org coursera.org futurelearn.com

Something that will help users find relevant training and be more inviting. This should include searching by topics. Maybe presenting the user with links to filter by the most popular topics and lists of other topics in smaller.

A section containing the latest statistics like how many resources added in last month and how many users we have.

A section with all our content providers logos neatly tiled - each linking to their content provider page - and a link underneath saying 'join us' taking them to the about page.

**Comment by fbacall** [comment]
Could have a list of most popular topics. Here is the query to get a hash that maps the top 5 most popular topics to the number of things linked to it:
```
ScientificTopicLink.all.group(:term_uri).order('count_id DESC').limit(5).count('id').map { |k,v| [EDAM::Ontology.instance.lookup(k), v] }.to_h
```

**Comment by njall** [comment]
Part of https://github.com/ElixirTeSS/TeSS/issues/358
