### ISSUE TITLE
Target audience for cambridge scraper needs fixing

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#483]
CSS changes have made one of the filters:

<span style="color:#FF0000">Please be aware that these courses are only free for University of Cambridge students. All other participants will be charged a registration fee in some form. Registration fees and further details regarding the charging policy are available here.''<span style="color:#FF0000">

This whole bullet needs to be excluded from target audience parsing bit

**Comment by fbacall** [comment]
That scrapers uses their JSON API though, the mistake is on their end:
https://www.training.cam.ac.uk/api/v1/provider/BIOINFO/programmes?fetch=events.sessions,events.topics&format=json
