### ISSUE TITLE
sw.js logspam

### ISSUE THREAD

**Issue by knirirr** [ElixirTeSS/TeSS#485]
Something (presumably the moment package) is querying /sw.js and causing a lot of logspam when the route isn't recognised.

**Comment by fbacall** [comment]
Which pages are you seeing this on?

**Comment by knirirr** [comment]
From my logs, here's one example:

    Started GET "/search?utf8=%E2%9C%93&q=python" for 127.0.0.1 at 2017-09-28 16:22:44 +0100                                                                

..followed, after all the rendering by:

    Started GET "/sw.js" for 127.0.0.1 at 2017-09-28 16:08:07 +0100                                                                                                                                                                                                                                                  AbstractController::ActionNotFound (The action 'nothing' could not be found for ApplicationController):

**Comment by fbacall** [comment]
I can't reproduce this.

Can you look in the "Network" tab of Firefox's dev tools and see what is there under the "Cause" column when it tries to load sw.js?

**Comment by knirirr** [comment]
I'm afraid that I wasn't able to spot anything when I looked there last week.

**Comment by fbacall** [comment]
Could it be coming from a different app?

Some googling of "sw.js" led to talk of React. Did you maybe have a React application open in another tab that was previously running on the same port as TeSS is now on?

**Comment by knirirr** [comment]
I'm afraid not - I don't use React and though I've had some applications running Vue.js and Meteor code but none were operating at the time.

I suggest that the ticket be closed and I will try re-installing things and clearing out my cache here to see if that helps.
