### ISSUE TITLE
Geolocation as a background job

### ISSUE THREAD

**Issue by knirirr** [ElixirTeSS/TeSS#501]
Nomintatim Geocoder lookups are already in use in TeSS (#49), but adding them to the scrapers (https://github.com/ElixirTeSS/TeSS_scrapers/issues/49) seems to hit Nominatim's rate limits (https://operations.osmfoundation.org/policies/nominatim/). 

Another option is to queue background requests with Sidekiq only for new records and those where the location has changed. 

We could also attempt to set up our own Nominatim instance at OeRC, though the requirements might be excessive for the funds available.

**Comment by knirirr** [comment]
Discussion on 17/1/18 suggested removing the geocoder lookups from scrapers, instead doing the lookups from a background job on TeSS. 

Runing a Nominatim server at OeRC would indeed be too expensive, IT services have confirmed.

**Comment by fbacall** [comment]
Check if we are identifying ourselves in the Refer or User-Agent headers, as is required by point 2 of the requirements: https://operations.osmfoundation.org/policies/nominatim/

**Comment by knirirr** [comment]
This version calls the GeocodingWorker via `rake tess:update_lat_lon` and updates the values directly rather than going via an EditSuggestion. There appear to be about 1200 events which need updates (and > 1600 which don't) so that would take about 20 hours if 1 is run per minute. I am assuming that the rake task would be called once per week or so.

Both this change and the corresponding change to the scrapers (referenced above) are in branches and so can be merged or deleted as is seen fit.
