### ISSUE TITLE
Remove suggestion notification/edit form add

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#505]
It would make sense to remove the suggestions within the edit form now that we’ve expanded the suggestions scope and have simpler mechanisms for accepting/rejecting within the show page

<img width="239" alt="screen shot 2018-01-16 at 13 44 30" src="https://user-images.githubusercontent.com/860475/35104602-36dbdf9e-fc61-11e7-87a2-e60c92290265.png">

**Comment by knirirr** [comment]
Looks like this has already been done - there aren't any edit suggestions shown in the edit form as far as I can tell.
