### ISSUE TITLE
Add structure to operations

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#509]
EDAM Operations/Topics list needs structure.

In https://tess.elixir-europe.org/edam/terms.json we need to be able to somehow express the hierarchical structure so that the workflow editor can present and understand where a term comes in relation to other terms. e.g. 

<img width="542" alt="screen shot 2018-03-12 at 17 58 59" src="https://user-images.githubusercontent.com/860475/37300907-137fda90-261f-11e8-917d-ac9c8a2de744.png">

Maybe add another attribute childOf or parentOf. Or list them in a nested JSON format

**Comment by fbacall** [comment]
Can add either a "parent" URI or array of "children" URIs - which is preferable?

**Comment by njall** [comment]
Probably parent. If a term gets deleted they usually change the parentOf property to DeprecatedClass. That seems simpler/easier to manage than finding the parent of a deprecated class and removing it from the list of children
