### ISSUE TITLE
Monitoring script

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#511]
A script to, at least initially, flag any records which respond with problems e.g. 4** 5** errors.

**Comment by knirirr** [comment]
I note that some URLs, such as https://www.bits.vib.be/training-list/111-bits/training/previous-trainings/128-comparative-genomics-in-eukaryotes, return a 400 even though they are fine in a browser. I presume that their server doesn't like the user agent.

**Comment by njall** [comment]
Of relevance to https://github.com/ElixirTeSS/TeSS/issues/580
