### ISSUE TITLE
Monitoring Script integration

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#517]
Store the results of the rake task in TeSS. Add a new table for event monitoring results with:
An association to the resource being monitored
failed_at: datetime
last_failed_at: datetime

The monitoring script can then set failed_at & last_failed_at to the current time on the first fail. 
Then every subsequent fail it can set the last_failed_at to the current time. 
If it passes the monitoring test, they can both be reset to nil. 

After that, you can add a helper method like def failing? - which will determine if there is a diff of over 3 days between failed_at and last_failed_at. 

Then we can start hiding any resource.failing? from non-privileged users; and add an exclamation icon next to it for privileged users

**Comment by njall** [comment]
Also, Finn pointed out we should store a failure_count that gets incremented each failed test. This may help us to discriminate different kinds of failures in the future

**Comment by knirirr** [comment]
This is in a branch deployed on tess.oerc, where I'm currently running the URL checks so this can all be tried out.

There's one major feature missing at present, which is hiding Event and Material records from non-admins; I'd think that the best way to do it would be to exclude them entirely from the index method and I'm not yet sure of a good way to do that. Meanwhile, a broken link icon will be shown to admins and any ExternalResource which is failing in this way is not shown on the relevant record's page.

**Comment by fbacall** [comment]
I can't seem to comment directly on the code, but in the `Searchable` module you can check:
`method_defined?(:failing)` instead of catching an exception

**Comment by knirirr** [comment]
If this is OK to merge in then I could do so and deploy it to production.
How often should the rake script be run to check for broken URLs?

**Comment by fbacall** [comment]
One more small change you could make is to make the `failing` Solr field into a boolean rather than a string. Might make searches a bit faster. Otherwise I think its OK to merge

**Comment by fbacall** [comment]
and I think we should run it once per day, a few hours after the scrapers have run
