### ISSUE TITLE
Check geolocation service

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#521]
I added and ran a new scraper for Sheffield Bioinformatics Core but the map plot is not showing. Would you mind looking into why not? 

I figured with the postcode something should be returned - Is the service running, does the API use the postcode as priority, does the address exist?

https://tess.elixir-europe.org/events/best-practices-in-research-data-management-for-biological-sciences

**Comment by fbacall** [comment]
Just had a look at this, there were a lot of errors:
```
NoMethodError: undefined method `geocoding_api_lookup' for #<Event:0x007f77b8e0f128>
```

I think we need to restart sidekiq whenever we do an update to TeSS. Maybe need to look into how others use sidekiq in production.

**Comment by fbacall** [comment]
Also, it seems that Geocoder/nominatim is not returning any results :( 

Not sure if we are rate limited or what...

**Comment by fbacall** [comment]
You could add it to the `update_tess.sh` script.

**Comment by knirirr** [comment]
Am I correct in thinking that the lookups were removed from the scrapers themselves and moved to a rake task? If so then that task isn't currently set to run via cron (perhaps it should go in the scraper wrapper). If no-one objects I'll run it in a moment to see what we get.

**Comment by fbacall** [comment]
The lookups are done asynchronously via sidekiq jobs

**Comment by knirirr** [comment]
It looks like the problem with these Sheffield events is that the address field is being passed to Nominatim and that doesn't produce any hits. A manual search with the postcode does work, though:

https://tess.elixir-europe.org/events/best-practices-in-research-data-management-for-biological-sciences

So, what would probably fix this is a second lookup with the postcode if the address fails. Adding the postcode onto the start or end of the address doesn't help here.

**Comment by knirirr** [comment]
When trying Geocoder lookups I've been getting a response that the page location has changed, so perhaps Geocoder is out-of-date and isn't querying the correct URL.
I've added a branch where a direct query to Nominatim is made using what fields we've got of those they accept.

**Comment by knirirr** [comment]
Could this be closed now? AFAICT any further changes would be part of #533
