### ISSUE TITLE
Have 'show all' button for map view of events

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#523]
Have a button that, when pressed, displays all events on the events map tab at the same time. Can set per_page to very high

**Comment by njall** [comment]
On the maps tab: https://tess.elixir-europe.org/events#map
Beneath the map tab and above the map itself

**Comment by knirirr** [comment]
I've added such a button, and made a few other changes as well (it's in a branch).
One odd thing is that thought the code in master only generates pins for events with coordinates it seems that there are fewer events shown than ones which have them. I'm not yet sure why this is.

**Comment by njall** [comment]
Thanks, I'm going to refactor some stuff before merging. The JS for the maps needs cleaning up a bit.
