### ISSUE TITLE
Luxembourg not listed as node 

### ISSUE THREAD

**Issue by rolandkrause** [ElixirTeSS/TeSS#530]
https://tess.elixir-europe.org/events/new

Luxembourg is missing from the list of Nodes

<img width="372" alt="screen shot 2018-06-07 at 10 20 56" src="https://user-images.githubusercontent.com/2631086/41087271-833f45bc-6a3c-11e8-9063-0210ca94082e.png">

**Comment by fbacall** [comment]
Thanks for reporting this, I've added Luxembourg and some other missing nodes.
