### ISSUE TITLE
Improve/debug the FAIRSharing intergration

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#532]
Associated FAIRSharing resources are not displaying supplementary information from the FAIRSharing API. Usually the association between TeSS and FAIRSharing is made via a URL. 
The external resources are displayed via app/views/common/_external_resource.html.erb
And external data is retrieved from the fairsharing API using an AJAX call in app/assets/javascript/fairsharing.js to a FAIRSharing API endpoint.

However, no extra info is being displayed; for example in https://tess.elixir-europe.org/materials/flymine-intro-videos

Could you investigate what the issue is?

**Comment by knirirr** [comment]
The issue would seem to be:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://fairsharing.org/api/all/summary/?search=variation&types=biodbcore,standard. (Reason: CORS preflight channel did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://fairsharing.org/api/all/summary?search=variation&types=biodbcore,standard. (Reason: CORS request did not succeed).
```

Not yet clear why that is, for a wget request to the same endpoint works as it should. I'm investigating it.

**Comment by knirirr** [comment]
There seem to be two things going on here:

1. I'm using Firefox, and that was giving me errors such as those mentioned above (this wasted some time). All was fine on Chrome.
2. There's a bug whereby ids with biodbcore in weren't being recognised as valid FAIRsharing IDs, even thought they're legitimate (deprecated) ones.

**Comment by knirirr** [comment]
This appears to be fixed.
