### ISSUE TITLE
Materials assignment in Event page

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#535]
In the Event edit form the user is given the ability to link their event to a TeSS material. This is often used to link to the slides/resources an event used. 

Currently it's facilitated by an autocomplete text box which is difficult to use. There's no context to help the user know which material is which. Underneath this field is the bio.tools integration which has a search box and displays lots of metadata about each tool result. 

Create a search client for TeSS in the same style and manner as the bio.tools integration. It should allow the user to type a query and display matching materials, which they can select the relevant one.  

Write a client that uses TeSS' json_api for the data, in a style similar to app/assets/javascripts/[biotools.js, fairsharing.js]

**Comment by knirirr** [comment]
I've put a draft version of this in the resource_api_535 branch.
This will need quite a bit of polish which I will probably have to do in September.

**Comment by njall** [comment]
- [ ] Search on key-up after 3 characters

- [ ] Run search on enter key press whenever the focus is set on the search box

- [ ] Replace the icon used with the book shaped material icon (as seen on 'Latest Content in TeSS' on main page)

- [ ] When clicked, the link to each material in the search results link to <root>/materials. Have them link to their TeSS resource page, but in a new tab. 

- [ ] Truncate text at 600 characters

- [ ] Add FAIRSharing association to Events (copy across from Material form)

**Comment by knirirr** [comment]
This has now been merged.
