### ISSUE TITLE
API endpoint to retrieve events with geolocation

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#537]
For use by the maps widget and the map view. 

Currently the map widget and map view request events and plot only those that have latitude and longitude. It would be good to have an endpoint that returns a paginated lists of events which only include geolocation information

**Comment by fbacall** [comment]
Maybe worth looking into this: https://github.com/ElixirTeSS/TeSS/blob/8d83587ca20fffcc32bc5b1650497b8dd8998c3e/app/models/event.rb#L83

we could have a filter "within <distance> of <location>".

If you wanted to get all the events with a lat/lon, you could set <distance> to something really high.
