### ISSUE TITLE
Mobile UI Tweaks

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#539]
- [x] Prevent the footer div from overlapping with the bottom of each pages contents  e.g
![screen shot 2018-07-12 at 14 32 07](https://user-images.githubusercontent.com/860475/42636318-5fb064fe-85e0-11e8-8e3c-87ee5ce92a90.png)

- [ ] On small screens only - have a closed collapsible element labelled Search Options which will contain the Search Box, Filters button, 'Show past events' button, and the Results Ordering dropdown. Selecting Search Options will open the collapsible div to reveal these options. This should be the same on the Materials tab and the Content providers tab with the Search, Filters, and Ordering options included

- [x] On the home page the magnifying button next to the 'Search training...' input goes onto a newline. in small screens. Attach the button and input together like seen in the Events and Materials index pages

**Comment by knirirr** [comment]
These classes look as though they may do the trick for the collapsible element:

https://getbootstrap.com/docs/3.3/css/#responsive-utilities
