### ISSUE TITLE
Identifiers.org integration part 2

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#545]
Have cite button on each resource page that has a copiable identifiers.org ID. Maybe similar to Githubs 'Copy to clipboard' style feature
![screen shot 2018-08-17 at 16 44 29](https://user-images.githubusercontent.com/860475/44277162-aa632b80-a241-11e8-9a6b-45a5cb4cc8c4.png)

**Comment by fbacall** [comment]
@njall you might want to change the wording in the popup box
