### ISSUE TITLE
Add a facet for "Community" (/ "Use Case")

### ISSUE THREAD

**Issue by egonw** [ElixirTeSS/TeSS#548]
At this moment things (events, material, ...) can be linked to a ELIXIR Node, but it would be really useful to be able to link something to an ELIXIR Community too (formerly "Use Case"). These are the currently approved ones:

![image](https://user-images.githubusercontent.com/26721/44650079-f0f51a80-a9e5-11e8-9ecd-4941ad23499f.png)

**Comment by njall** [comment]
As part of #358
