### ISSUE TITLE
Replace topic/operation selector with Edam Select

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#579]
Within materials/events/workflows forms, the user can type in their scientific topic or operation and matches from the EDAM ontology will show up. It's not a good solution for navigating through the ontology, which is necessary if you are not familiar with it. 

Replace the field with Ivan Kuzmins Edam Select Javascript widget

https://gl.cs.ut.ee/inkuzmin/edam-select/tree/vanilla-js

**Comment by inkuzmin** [comment]
Hi @njall !

I've just published it at the NPM (https://www.npmjs.com/package/edam-select) and written the documentation up (https://inkuzmin.github.io/edam-select/). Hope it helps to reuse it.
