### ISSUE TITLE
Metadata 2.0

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#585]
The metadata for events and materials in TeSS should change to be that of the stable releases of Bioschemas. 

1. Bioschemas has had lots of concensus from Life science trainers
2. TeSS parses Bioschemas to aggregate, and maps this data to our own metadata. It would be more convinient if our metadata was perfectly aligned with Bioschemas (therefore no mapping needed)
3. The Bioschemas properties have descriptions which could be used in TeSS forms to help users disambiguate fields.
4. The same course can be run over multiple instances at different times and/or locations. TeSS does not currently allow for this, which means instances of the same course need to be entered each time. Bioschemas has the Course and CourseInstance paradigm, which allows a course to be described a long with all of its instances. This is useful to TeSS as it lowers curation overheads and duplication of data.   

 
To do this;
- [ ] Create a mapping between TeSS fields and the relevant Bioschemas fields. Events should map to Course and CourseInstance; and Materials should map to TrainingMaterials.
- [ ] Decide if any Bioschemas fields that do not map are worth adding into TeSS
- [ ] If there are TeSS fields that don't exist in Bioschemas (such as Content Provider and Nodes), these unmappable metadata fields should remain in TeSS. 
- [ ] Updating the metadata will require a new version of the API to be created as well as a mapping made to the old one to keep it functioning as normal. Widgets and scrapers that use the old API will have to migrate to use the new one.

**Comment by 03c** [comment]
#tess/bio
