### ISSUE TITLE
AAI Login button wrong 

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#605]
I was recently reviewing the training plans of the ELIXIR AAI Task, and when discussing with Mikael Linden (cc:ed here) he mentioned that the TeSS login page (https://tess.elixir-europe.org/users/sign_in) has a wrong ELIXIR Log-in button. It says "Log in with ELIXIR credentials", so it doesn't follow the standard described at https://elixir-europe.org/services/compute/aai/login-guidelines. Mikael has tried to contact TeSS support to get this changed, but I guess Niall has left already. Pascal would you be able to forward this information to whoever is in charge of TeSS now?

**Comment by AnnalisaMilano** [comment]
Hi, Chris. Are there any updates on this? Let me know if you need any information on the Training side. Annalisa

**Comment by christopherchild** [comment]
Code complete: fc58f4ea95eccb2b0ac1796f2fffb85926b647af

**Comment by christopherchild** [comment]
This is now live.
