### ISSUE TITLE
View Bioschema links are broken

### ISSUE THREAD

**Issue by rgaiacs** [ElixirTeSS/TeSS#609]
https://tess.elixir-europe.org/about/registering#automatic has links to view BioSchemas:

- https://bioschemas.org/specifications/Event/specification/
- https://bioschemas.org/specifications/TrainingMaterial/specification/

both links end up in "Page not found".

**Comment by christopherchild** [comment]
Thank you for reporting this bug.

Would you be able to submit a PR with the updated URLs?
