### ISSUE TITLE
Update Ruby version

### ISSUE THREAD

**Issue by fbacall** [ElixirTeSS/TeSS#615]
`2.4` is EOL,

Try 2.6 or 2.7?

See: https://github.com/ElixirTeSS/TeSS/blob/master/.ruby-version

**Comment by knirirr** [comment]
I'm using 2.6 with Rails 6 for the new version of FAIRsharing.

**Comment by fbacall** [comment]
Were there any sticking points?

**Comment by knirirr** [comment]
None; I found the upgrade from 2.4 and Rails 5 to be pretty seamless. But, we're running an API-only Rails application so I might not have spotted any issues related to templates etc.

**Comment by 03c** [comment]
closed #660
