### ISSUE TITLE
Update Rails to version 6

### ISSUE THREAD

**Issue by 03c** [ElixirTeSS/TeSS#619]
I thought it would be a good idea to update Rails to version 6.

The upgrade guide is here [https://guides.rubyonrails.org/upgrading_ruby_on_rails.html](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html).

**Comment by fbacall** [comment]
Just glancing over that, the only potential issues I can see are migrating to `webpacker` (since the TeSS JS is a bit messy), and possibly some of the auto-loading changes.

It's definitely worth doing, though.

**Comment by christopherchild** [comment]
Cheers, that is good to know.

I had a play over the weekend and I did have an issue with the new auto-loading, but I think it's just going to require a name change on some classes/modules (`EDAM` was the first error, might be more). 

I wasn't able to fully test the new `webpacker`, it all installed fine, but an issue with Solr prevented me from getting any further.

I was going to just include this the the same PR was the Ruby upgrade, but I think it is going to require a little more time.

**Comment by christopherchild** [comment]
Just a though - might be worth checking the Java version for the Solr problem.

**Comment by fbacall** [comment]
What's the error?

If the version of the `sunspot` gem has changed, sometimes you need to delete the `solr` directory at the route and have the gem regenerate all the configuration.

**Comment by christopherchild** [comment]
Yeah, I did update he sunspot gem. I did also try deleting the solr directory. 

The error was a `NullPointerException`.

These two questions on stackoverflow were the closest I could find:

[https://stackoverflow.com/questions/48058616/rails-with-solr-sunspot-java-lang-nullpointerexception](https://stackoverflow.com/questions/48058616/rails-with-solr-sunspot-java-lang-nullpointerexception)
[https://stackoverflow.com/questions/36434823/solr-webadmin-error-500](https://stackoverflow.com/questions/36434823/solr-webadmin-error-500)

**Comment by fbacall** [comment]
Might be worth checking the Java version then. We say Java 8 in the install docs, but that might be too old.

**Comment by 03c** [comment]
closed #660
