### ISSUE TITLE
Layout and Presentation Updates (UI)

### ISSUE THREAD

**Issue by 03c** [ElixirTeSS/TeSS#629]
Design Document: [UI Update](https://docs.google.com/document/d/1tOWIFlznxgcVBu3NhkdWj0y9FSx4_Jub6RjbnMqtXwo/edit?usp=sharing)

Figma: [Mockup](https://www.figma.com/file/Q3BluLFEC0xVEWXgEVXmsg/TeSS-styling?node-id=2%3A452)

Xenia has kindly worked on the design and produced the Figma Mockup.

Other work to be completed as part of the UI work:

- [ ] Other Installations - There are a few other installations of TeSS, it would be good to have a page where we link to them.
Digital Research Skills Australasia (DReSA) - https://dresa.org.au/
the training portal for the photon & neutron community - https://pan-training.hzdr.de/
- [x] Help and training pop-ups on macOs: There is significant reliance on pop-ups for guides; however these do not work on macOs Safari and macOs Firefox and nearly half of the participants use macOs Safari as their default browser.
- [ ] The e-Learning pages should have an add button like other pages. It is confusing to expect people to know that they must go to the materials page in order to add some e-learning.
- [ ] Search and filter issues: A user can search and then apply a filter but not filter and then apply a search; a filter only has “OR” functionality for selecting tags under a category and most participants want “AND”; the arrangement of categories for filters desired by the users is not the same as currently offered by the TeSS; Adjust the search engine mechanism. At least it should provide the same results as filter has; Ensure that search also searches the keywords

**Comment by christopherchild** [comment]
#479

**Comment by 03c** [comment]
See #630 for suggestions
