### ISSUE TITLE
Some design suggestions

### ISSUE THREAD

**Issue by bedroesb** [ElixirTeSS/TeSS#630]
**Is your feature request related to a problem? Please describe.**
If I visit the website I think that it looks quite busy. Many borders and shadows are seen + the header with all the layers is a bit distracting.

**Describe the solution you'd like**
 I quickly made in my browser some changes to make it look lighter:

before:

![Screenshot from 2020-11-05 12-11-43](https://user-images.githubusercontent.com/44875756/98234995-847ceb00-1f61-11eb-8f8d-295f75ae9a77.png)

after:

![Screenshot from 2020-11-05 12-11-29](https://user-images.githubusercontent.com/44875756/98235008-89da3580-1f61-11eb-9fd1-810bed03d748.png)

- less layers in the header + only one color
- no border in search bar of the header
- breadcrumbs have on top and bottom the same margin
- no border or shadow around the wrapper
- border around the whole sidepanel + 4px border radius
- only padding on the left side for the content
- the material panels have no shadow anymore and have a border radius of 4px just like the rest
- more padding around the content of the footer
- all border and background colors the same type of grey 

or with white layer in the header:

![Screenshot from 2020-11-05 14-57-33](https://user-images.githubusercontent.com/44875756/98250269-8651a900-1f77-11eb-8b9e-939821c43886.png)

**Additional context**
These are just some ideas and I have no idea whether there were plans in changing the layout.

**Comment by christopherchild** [comment]
Sorry - I've only just seen this.

Thanks for the feedback!

There are some general plans to streamline the UX but no concrete plans to update the styling. I do agree with your points, shadows do seem a little outdated.

I'll keep this in mind when planning the UX changes.

**Comment by bedroesb** [comment]
great!
