### ISSUE TITLE
Searching for "CWL" fails to bring up tagged event

### ISSUE THREAD

**Issue by mr-c** [ElixirTeSS/TeSS#654]
**Describe the bug**
Searching for "CWL" fails to bring up tagged event

**To Reproduce**
1. https://tess.elixir-europe.org type "CWL" in the search box
2. https://tess.elixir-europe.org/search?utf8=%E2%9C%93&q=cwl

**Expected behavior**
No events are listed, like https://tess.elixir-europe.org/events/bioinformatics-workflow-management which includes "CWL" both in the full text and in the keywords

**Comment by mr-c** [comment]
Even searching using the separate Events search engine (which should be integrated in the main search) there are zero results for CWL

https://tess.elixir-europe.org/events?q=cwl

**Comment by 03c** [comment]
See #628 where I am compiling a a list of search related issues to fix.
