### ISSUE TITLE
Backend collection association improvements

### ISSUE THREAD

**Issue by fbacall** [ElixirTeSS/TeSS#726]
Currently uses 2 join tables: `collection_events` and `collection_materials`.

Change to use a single table `collection_items` with a polymorphic field.

Also add extra fields:
- [ ] `pos` (Int) - For ordering items in the collection
- [ ] `comment` (Text) - Describes the role of the item in the collection

#724

**Comment by fbacall** [comment]
@DaanVanVugt would this be useful at all for your collections work? and would you be interested in looking into it? :)

**Comment by DaanVanVugt** [comment]
I think it makes sense to clean up a bit and remove some unused code, but it would not bring any new features on the near term. Technical debt I guess. If I find some time I might take a stab at it.

**Comment by fbacall** [comment]
I actually have some time today to look into it
