### ISSUE TITLE
Keyword parsing

### ISSUE THREAD

**Issue by DaanVanVugt** [ElixirTeSS/TeSS#792]
**Is your feature request related to a problem? Please describe**

The keywords facet is getting full and hard to scan on staging.taxila.nl. Many of these keywords actually correspond to other fields, where we have dictionaries.

**Describe the solution you'd like**

Extend the dictionaries to have keyword names / regexes, and automatically convert a keyword to a dictionary field if matching.

**Describe alternatives you've considered**

Could implement this at the scraper level, but sources that provide keywords typically do not sort them into our categories. By doing it 'globally' we could reduce the maintenance burden for everyone.
An option would be to use these as edit suggestions, instead of directly applying them (but we would like to try direct application on our instance)

**Additional context**

![taxila keywords list 2023-01-04](https://user-images.githubusercontent.com/35944/210521725-925879b2-d20c-481e-868d-f957983b4fd2.png)

**Comment by fbacall** [comment]
Implemented by #828
