### ISSUE TITLE
Event end date is scrape date, even before start date

### ISSUE THREAD

**Issue by bencomp** [ElixirTeSS/TeSS#862]
**Describe the bug**

In Taxila, events that are scraped from Leiden University Libraries' events page often have end dates that come before their start dates. These end dates are then updated daily, when the scraper runs, to set the scrape date as the end date.

**To Reproduce**

  1. Go to [content provider Universiteit Leiden in Taxila](https://taxila.nl/content_providers/universiteit-leiden)
  2. Observe that future events that do not span multiple days have today's date as the end date

**Expected behavior**

I expect that single-day events have the same start and end date.

**Screenshots**

This is an example listing of events, with one a series that has started but the others workshops that start and finish on the same day.

![future-event-listing](https://github.com/ElixirTeSS/TeSS/assets/1303898/7cb8c456-bac1-4767-8298-94dc4fcd1c3b)

**Desktop (please complete the following information):**
  - OS: MacOS
  - Browser: Firefox
  - Version: 114

**Additional context**

I think this relates to `parse_dates` in `event_ingestion.rb`, as the `leiden_ingestor` directly gets the start and end dates from `parse_dates`.

**Comment by mikesndrs** [comment]
I will take a look at it

**Comment by bencomp** [comment]
It looks like this was fixed by #866. Thanks!
