### ISSUE TITLE
Map always loads (but never show) under Firefox, Ubuntu 22.04

### ISSUE THREAD

**Issue by richelbilderbeek** [ElixirTeSS/TeSS#897]
**Describe the bug**

When creating an event, one can fill in an address. However (and see the screenshot), the map never actually loads.

**To Reproduce**

  1. Go to 'Create Event'
  2. Edit 'Address'
  3. Observe the map always loading

**Expected behavior**

I expect a map to show.

**Screenshots**

![Screenshot from 2023-10-20 11-03-08](https://github.com/ElixirTeSS/TeSS/assets/2098230/dab768f5-b8ee-448b-ab08-85e07b66704f)

**Desktop (please complete the following information):**
  - OS: (e.g. iOS): Ubuntu 22.04 LTS
  - Browser (e.g. chrome, safari): Firefox
  - Version (e.g. 22): current Ubuntu version

**Additional context**

I have no plugins (e.g. add-blockers) installed on Firefox.

**Comment by fbacall** [comment]
Should be fixed now
