### ISSUE TITLE
Include event date in event RSS feed

### ISSUE THREAD

**Issue by fbacall** [ElixirTeSS/TeSS#942]
Currently the actual date of the event is not included anywhere in the RSS item.

One suggestion is to use the event's start date in the RSS item's `pubDate`, but I'm not sure if this would be a good idea (how do RSS readers handle dates in the future etc.).

Perhaps just include it in the description?

**Comment by fbacall** [comment]
@mikesndrs and @DaanVanVugt - any opinion on this?

**Comment by DaanVanVugt** [comment]
Description or title would be my preference. Pubdate is risky
