### ISSUE TITLE
Language of instruction/material

### ISSUE THREAD

**Issue by cwant** [ElixirTeSS/TeSS#994]
**Is your feature request related to a problem? Please describe**

Looking through the various models, I was unable to find a language field in either `Event` or `Material`.

**Describe the solution you'd like**

Ideally there would be a search facet that allows users to filter content by language.

**Describe alternatives you've considered**

I guess as an alternative one could (ab)use the keyword field.

**Additional context**

Happy to work on this feature (as a bilingual country, we need it), but wanted to sanity check the idea here first.

**Comment by fbacall** [comment]
Yeah, this would be useful for sure.

I would say try and constrain the values with some kind of standard (ISO 639?) instead of having it be a free-text field.
